### ISSUE TITLE
Receive only header data, what is wrong

### ISSUE THREAD

**Issue by radebold** [TA2k/ioBroker.volvo#19]
![grafik](https://github.com/TA2k/ioBroker.volvo/assets/25064101/d46cdc28-0d2d-4dec-9544-093ca0358896)

As in the screenshot visible, I received only header data, no details.
I have a XC90 recharge, so a hybrid car.
The flag in the configuration for electric cars I don't set.

In the developer portal I had only create a app, only the name and then I copied the api key

What can I do?

Thx
Thomas

**Comment by TA2k** [comment]
What is debug log saying

**Comment by radebold** [comment]
> What is debug log saying

can any help me with my issue or my car, maybe the problem is, it is from 2024

**Comment by radebold** [comment]
now it works, without any change
