### ISSUE TITLE
XC90 recharge - error: Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application.

### ISSUE THREAD

**Issue by radebold** [TA2k/ioBroker.volvo#20]
I have insert the key and also the credentials.
If I set the flag "use new api for electrcan cars" I received this error

![grafik](https://github.com/TA2k/ioBroker.volvo/assets/25064101/f9ed2ee5-3350-4b3c-9be2-66ce9cd1b8ac)

I had created a app in my dev account and set all flags in this app.
What is going wrong here?

Thx
Thomas

**Comment by radebold** [comment]
can any help me with my issue or my car, maybe the problem is, it is from 2024

**Comment by Robbi12** [comment]
The same Problem here

**Comment by radebold** [comment]
don't exist anymore
