### ISSUE TITLE
Upgrade to API Version 2

### ISSUE THREAD

**Issue by esusxunil** [TA2k/ioBroker.volvo#27]
Since today (30.04.2024) the Version 1 of the Volvo Connected Vehicle API is not available anymore.

{"error":{"message":"GONE","description":"Version 1 is removed. See https://developer.volvocars.com/apis/connected-vehicle/v2/overview/"}}

Are there already plans to migrate the adapter to Version 2?

**Comment by TA2k** [comment]
I need a login with password and vcapi key

**Comment by TA2k** [comment]
die GitHub version ist ungetestet angepasst

**Comment by esusxunil** [comment]
Erst einmal vielen Dank fuer die schnelle Reaktion.

Ich habe Version 0.1.2-beta.0 installiert und das meiste funktioniert, ich bekomme zumindest die Werte wie Ladestand, die mich interessieren.

Es gibt beim Start noch 2-3 Requests die wohl ins Leere gehen.

Aus dem Logs kann ich noch entnehmen, dass die VIN korrekt zurueckgeliefert wird.

Dann folgt folgende Fehlermeldung:

```
2024-04-30 16:23:06.771 - error: volvo.0 (17343) AxiosError: Request failed with status code 406
2024-04-30 16:23:06.771 - error: volvo.0 (17343) {"error":{"message":"NOT_ACCEPTABLE","description":"Not Acceptable"}}

```
kurz danach noch folgende Fehlermedlung:

```
2024-04-30 16:23:07.077 - error: volvo.0 (17343) Error: environment failed
2024-04-30 16:23:07.078 - error: volvo.0 (17343) AxiosError: Request failed with status code 404
2024-04-30 16:23:07.078 - error: volvo.0 (17343) {"statusCode":404,"message":"Resource not found"}
```

Ab der oilLevelWarning sieht dann wieder alles gut aus.

Der erste Fehler tritt auch nur einmalig auf, der zweite bei jedem Update.

Im Anhang einmal ein komplettes Log (auf Log All), habe nur die VIN und den Accesstoken maskiert.

[volvo.log](https://github.com/TA2k/ioBroker.volvo/files/15167328/volvo.log)

**Comment by esusxunil** [comment]
Gerade Beta1 installiert und ausprobiert.

Der zweite Fehler, der bei jedem Refresh auftrat ist weg.

Nur noch der Fehler beim Start ist noch vorhanden mit folgender zusaetzlichen Ausgabe:


```
volvo.0 | 2024-04-30 22:35:30.935 | error | get command list failed
volvo.0 | 2024-04-30 22:35:30.936 | error | AxiosError: Request failed with status code 406
volvo.0 | 2024-04-30 22:35:30.936 | error | {"error":{"message":"NOT_ACCEPTABLE","description":"Not Acceptable"}}
```

**Comment by TA2k** [comment]
nochmal installieren

**Comment by kschaumann** [comment]
> nochmal installieren

Funzt bei mir wieder, alle Werte die ich geprüft habe sind aktuell. Im Log keine Fehler

**Comment by TA2k** [comment]
https://github.com/TA2k/ioBroker.volvo/commit/4976bbe86321549b9492dfc50584c947f2447c6f
