### ISSUE TITLE
State does not exists error

### ISSUE THREAD

**Issue by TiDO2k** [TA2k/ioBroker.volvo#6]
**Describe the bug**  
I use Node-Red in iobroker.
When I want to set the state of a remote service, there is the following error:
"state volvo0.abcdefg.remoteclimatization.stop does not exist in the iobroker"

Also when I want to start a remote service under iobroker -> objects it is not possible to start the service.

In the iobroker vwconnect adapter everything works fine.
what is the difference to volvo on call?

**To Reproduce**  
1. Go to objects in iobroker
2. Click on volvo0 -> FIN -> remote -> preclimatization/start
3. click the checkbox under value

**Versions:**  
 - Adapter version: 0.0.3
 - Node version: 12.20.0

**Comment by TA2k** [comment]
Node is not working with slashes in state name please use alias
