### ISSUE TITLE
Login broken?

### ISSUE THREAD

**Issue by andig** [TA2k/ioBroker.volvo#8]
I'm recently seeing HTTP 401 errors when logging in:

    {"errorLabel":"Unauthorized","errorDescription":"Invalid credentials"}

Credentials have not been changed. Is anyone else experiencing this?

**Comment by TA2k** [comment]
I cannot reproduce this

**Comment by andig** [comment]
Mhhm. Seems there‘s a new Volvo Api, too: https://developer.volvocars.com/volvo-api/extended-vehicle/

**Comment by TA2k** [comment]
This is correct, but the legacy is still working.

**Comment by andig** [comment]
Unfortunately not for me. The same EU credentials used to work until a few days ago:

```
2021-03-20 11:16:25.605 - info: volvo.0 (2878) starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.volvo, node: v12.21.0, js-controller: 3.2.16
--
2021-03-20 11:16:25.979 - error: volvo.0 (2878) null
2021-03-20 11:16:25.980 - error: volvo.0 (2878) Login failed
```

The HTTP 401 above is taken from the evcc implementation which I based on this repo.

**Comment by andig** [comment]
Update: user changed it's mind. Password apparently was changed. Closing as bogus :(
